version: "3.8"

services:
  postgres:
    image: postgres:17
    container_name: slicercar-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: car
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: slicercar-backend
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgres://postgres:123456@202.28.49.122:5432/car
      - NODE_ENV=development

  importer:
    build:
      context: .
      dockerfile: docker/importer.Dockerfile
    container_name: slicercar-importer
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgres://postgres:123456@202.28.49.122:5432/car
    volumes:
      - ./mongo-backup:/app/mongo-backup:ro
      - ./backend:/app/backend:ro
      - ./docker/mongo_to_postgres_import.js:/app/mongo_to_postgres_import.js:ro
    command: ["node", "mongo_to_postgres_import.js", "--dir", "./mongo-backup", "--sync"]

  admin:
    build: ./admin-dashboard
    container_name: slicercar-admin
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://backend:5000

  frontend:
    build:
      context: ./frontend
    container_name: slicercar-frontend
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
    volumes:
      - ./frontend:/app
    stdin_open: true
    tty: true
    depends_on:
      - backend

volumes:
  postgres-data: